### ISSUE TITLE
我的多用户管理插件改好了

### ISSUE THREAD

**Issue by yhl452493373** [gofrp/plugin#5]
我发现我们都是国人，就不写憋足英文了

仓库地址：https://github.com/yhl452493373/frps-multiuser

+ 支持多用户
+ 增加管理界面，支持国际化，支持根据浏览器自动切换深色模式
+ 支持在线`创建`、`删除`、`启用`、`禁用`用户
+ 支持根据`用户`、`token`、`备注`进行搜索
+ 支持对每个用户进行`端口`，`自定义域名`，`二级域名`限制

**Comment by fatedier** [comment]
你可以参考格式提 PR 加在这里: https://github.com/gofrp/plugin#%E4%B8%AD%E6%96%87%E6%8F%92%E4%BB%B6

**Comment by yhl452493373** [comment]
> 你可以参考格式提 PR 加在这里: https://github.com/gofrp/plugin#%E4%B8%AD%E6%96%87%E6%8F%92%E4%BB%B6

直接提PR哇？
